version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
