# Stage 1: Build the application
FROM node AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
ENV GENERATE_SOURCEMAP=false 
RUN npm run build; exit 0

# Stage 2: Serve the application using Nginx
FROM nginx:alpine

# Copy the build output from the builder stage to the Nginx webroot
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]