FROM node:14 as build

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

# Copy the build output from the build image to the Nginx webroot
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]