version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "443:443"
    networks:
      - app-network
    # volumes:
    #   - /3dportfolio/cert:/certs

networks:
  app-network:
    driver: bridge
